// <auto-generated />
using GestionEstudiantil.Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionEstudiantil.Infraestructura.Migrations
{
    [DbContext(typeof(BaseDeDatosContexto))]
    [Migration("20250716001259_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("GestionEstudiantil.Dominio.Entidades.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Creditos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("GestionEstudiantil.Dominio.Entidades.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("GestionEstudiantil.Dominio.Entidades.EstudianteAsignatura", b =>
                {
                    b.Property<int>("EstudianteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EstudianteId", "AsignaturaId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("EstudiantesAsignaturas");
                });

            modelBuilder.Entity("GestionEstudiantil.Dominio.Entidades.EstudianteAsignatura", b =>
                {
                    b.HasOne("GestionEstudiantil.Dominio.Entidades.Asignatura", "Asignatura")
                        .WithMany("EstudiantesInscriptos")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEstudiantil.Dominio.Entidades.Estudiante", "Estudiante")
                        .WithMany("AsignaturasInscritas")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("GestionEstudiantil.Dominio.Entidades.Asignatura", b =>
                {
                    b.Navigation("EstudiantesInscriptos");
                });

            modelBuilder.Entity("GestionEstudiantil.Dominio.Entidades.Estudiante", b =>
                {
                    b.Navigation("AsignaturasInscritas");
                });
#pragma warning restore 612, 618
        }
    }
}
